### ISSUE TITLE
socawebui fails to start: ImportError url_encode from werkzeug

### ISSUE THREAD

**Issue by bsmith94** [awslabs/scale-out-computing-on-aws#2]
socawebui.sh fails to start the webservice. In application_output.log:

```
ImportError: cannot import name 'url_encode' from 'werkzeug' (/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/werkzeug/__init__.py)
[2020-02-12 02:20:05 +0000] [11337] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/apps/soca/soca-soca-2/cluster_web_ui/app.py", line 12, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/apps/soca/soca-soca-2/python/3.7.1/lib/python3.7/site-packages/werkzeug/__init__.py)
```

**Comment by mcrozes** [comment]
Hi Brian -

Thank for the issue and PR. I was able to reproduce the issue and validated your fix


**What is broken?**

`flask_wtf` is a dependency for SOCA WebUI and now returns an `ImportError` post   `Werkzeug` package upgrade.

**Why?**

Werkzeug changed the url_encode function from `werkzeug.url_encode` to `werkzeug.urls.url_encode` in the new version they recently pushed (1.0.0 released 2020-02-06: https://werkzeug.palletsprojects.com/en/master/changes/#version-1-0-0)

**What could have be done to prevent this?**

SOCA enforces python version checks for some packages (https://github.com/awslabs/scale-out-computing-on-aws/blob/master/source/scripts/Scheduler.sh#L309). However, `werkzeug` is a dependency of `flask` and we were not doing any version check. As a temporary workaround, we will continue to rely on the latest version available on `pip` but bump `flask_wtf` to `0.14.3`

**Fix**

Future releases will include `requirements.txt` which will list all Python packages and version required by SOCA
