### ISSUE TITLE
cloudformation:DeleteStack missing on SOCAInstallerIamPolicy	

### ISSUE THREAD

**Issue by adimicoli-quantummotion** [awslabs/scale-out-computing-on-aws#73]
Hi SOCA support,

**Describe the bug**
cloudformation:DeleteStack missing on SOCAInstallerIamPolicy

**To Reproduce**
Run the installer.

**Screen output just before crash:**

```
======= Pre-requisites completed. Launching installer =======
 ⏳  Bootstrapping environment aws://238617245913/eu-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
 ❌  Environment aws://238617245913/eu-west-1 failed bootstrapping: AccessDenied: User: arn:aws:sts::238617245913:assumed-role/gitlab/i-00254a115a49200ea is not authorized to perform: cloudformation:DeleteStack on resource: arn:aws:cloudformation:eu-west-1:238617245913:stack/CDKToolkit/f7cc9be0-d13b-11ec-b350-02c769418277 because no identity-based policy allows the cloudformation:DeleteStack action
    at Request.extractError (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/envs/.nvm/versions/node/v16.15.0/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'AccessDenied',
  time: 2022-05-12T13:43:26.520Z,
  requestId: 'acee0e50-4285-4cca-9af3-5e44491ccbc6',
  statusCode: 403,
  retryable: false,
  retryDelay: 790.2864067354369
}
NOTICES
19836	AWS CDK v1 entering maintenance mode soon
	Overview: AWS CDK v1 is entering maintenance mode on June 1, 2022.
	          Migrate to AWS CDK v2 to continue to get the latest features
	          and fixes!
	Affected versions: framework: 1.*, cli: 1.*
	More information at: https://github.com/aws/aws-cdk/issues/19836
If you don’t want to see a notice anymore, use "cdk acknowledge <id>". For example, "cdk acknowledge 19836".
User: arn:aws:sts::238617245913:assumed-role/gitlab/i-00254a115a49200ea is not authorized to perform: cloudformation:DeleteStack on resource: arn:aws:cloudformation:eu-west-1:238617245913:stack/CDKToolkit/f7cc9be0-d13b-11ec-b350-02c769418277 because no identity-based policy allows the cloudformation:DeleteStack action
            _____ ____  _________ 
           / ___// __ \/ ____/   | 
           \__ \/ / / / /   / /| | 
          ___/ / /_/ / /___/ ___ | 
         /____/\____/\____/_/  |_|                     
        Scale-Out Computing on AWS
    ================================
    > Documentation: https://awslabs.github.io/scale-out-computing-on-aws/
    > Source Code: https://github.com/awslabs/scale-out-computing-on-aws/
====== Validating Default SOCA Configuration ======
Configuration file path: /home/gitlab-runner/builds/-gdhzcEn/0/alessandro/soca-dev/soca/installer/resources/src/../../default_config.yml
====== Validating AWS Environment ======
====== Trying to detect your IP. Use --client-ip to specify it manually instead ======
We determined your IP is 35.178.52.222/32. You can change it later if you are running behind a proxy
====== Validating SOCA Parameters ======
====== Verifying SOCA Configuration  ======
Configuration valid. 
====== Running CDK Bootstrap ======
 Error! Unable to bootstrap environment. Please run cdk bootstrap aws://238617245913/eu-west-1 -c base_os=centos7 -c account_id=238617245913 -c bucket=cs-adm-soca-238617245913-eu-west-1-prod -c ldap_user=socaadmin -c ldap_password=UzBjYVBhc3N3MHJk -c ssh_keypair=adm_keypair -c cluster_name=adm-soca -c cluster_id=soca-adm-soca -c region=eu-west-1 -c client_ip=35.178.52.222/32 -c create_es_service_role=True -c vpc_cidr=10.1.8.0/22 and fix any errors
 Error: 256 
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit status 1
```

**Expected behavior**
Installer is unable to delete Cloudformation stack cluster

**Please complete the following information about the solution:**
- [ ] Version: v2.7.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  SourceCode:
    General:
      S3Bucket: "solutions"
      KeyPrefix: "scale-out-computing-on-aws/v2.0.0"
```

- [ ] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository? no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? no
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes
- [ ] Were there any errors in the CloudWatch Logs? no

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by ahmedelz** [comment]
Fixed via this [commit](https://github.com/awslabs/scale-out-computing-on-aws/commit/c05e95be4c30307bac87dbc6d45914f52f5be1a1)

**Comment by adimicoli-quantummotion** [comment]
Fantastic, thanks for your help. :)
