### ISSUE TITLE
Error! Unable to bootstrap environment, Invalid IPv4 CIDR: ""

### ISSUE THREAD

**Issue by notnonot** [awslabs/scale-out-computing-on-aws#88]
**Describe the bug**
Once a custom vpc cidr block is specified, the script soca_installer.sh  fails to start

**To Reproduce**
execute ./soca_installer.sh script 

**Expected behavior**
execute successfully

**Please complete the following information about the solution:**
Version: 2.7.0

Region: [ap-northeast-1]

The error log is as follows:

====== Running CDK Bootstrap ======

jsii.errors.JavaScriptError: 
  @jsii/kernel.RuntimeError: Error: Invalid IPv4 CIDR: ""
      at Kernel._ensureSync (/tmp/tmpwu21lhlh/lib/program.js:8904:27)
      at Kernel.sinvoke (/tmp/tmpwu21lhlh/lib/program.js:8325:34)
      at KernelHost.processRequest (/tmp/tmpwu21lhlh/lib/program.js:11514:36)
      at KernelHost.run (/tmp/tmpwu21lhlh/lib/program.js:11474:22)
      at Immediate._onImmediate (/tmp/tmpwu21lhlh/lib/program.js:11475:46)
      at processImmediate (node:internal/timers:466:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/soca/installer/resources/src/cdk_construct.py", line 1076, in <module>
    install = SOCAInstall(app, user_specified_variables.cluster_id, env=cdk_env,
  File "/root/soca/installer/resources/src/envs/venv-py-installer/lib64/python3.9/site-packages/jsii/_runtime.py", line 111, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/root/soca/installer/resources/src/cdk_construct.py", line 106, in __init__
    self.security_groups()  # Create Security Groups
  File "/root/soca/installer/resources/src/cdk_construct.py", line 245, in security_groups
    self.soca_resources["scheduler_sg"].add_ingress_rule(ec2.Peer.ipv4(user_specified_variables.client_ip), ec2.Port.tcp(22), description="Allow SSH access from customer IP to scheduler")
  File "/root/soca/installer/resources/src/envs/venv-py-installer/lib64/python3.9/site-packages/aws_cdk/aws_ec2/__init__.py", line 39932, in ipv4
    return typing.cast(IPeer, jsii.sinvoke(cls, "ipv4", [cidr_ip]))
  File "/root/soca/installer/resources/src/envs/venv-py-installer/lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 149, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/root/soca/installer/resources/src/envs/venv-py-installer/lib64/python3.9/site-packages/jsii/_kernel/__init__.py", line 420, in sinvoke
    response = self.provider.sinvoke(
  File "/root/soca/installer/resources/src/envs/venv-py-installer/lib64/python3.9/site-packages/jsii/_kernel/providers/process.py", line 381, in sinvoke
    return self._process.send(request, InvokeResponse)
  File "/root/soca/installer/resources/src/envs/venv-py-installer/lib64/python3.9/site-packages/jsii/_kernel/providers/process.py", line 340, in send
    raise RuntimeError(resp.error) from JavaScriptError(resp.stack)
RuntimeError: Error: Invalid IPv4 CIDR: ""

Subprocess exited with error 1
 Error! Unable to bootstrap environment. Please run cdk bootstrap aws://xxxxxxx/ap-northeast-1 -c base_os=centos7 -c account_id=xxxxxxx -c bucket=xxxx-test -c ldap_user=xxxxang -c ldap_password=xxxxxxxIzNDU2Kio= -c ssh_keypair=xxxxurse -c cluster_name=test-2-16 -c cluster_id=soca-test-2-16 -c region=ap-northeast-1 -c client_ip= -c create_es_service_role=True -c vpc_cidr=10.9.0.0/16 and fix any errors
 Error: 256

**Comment by mcrozes** [comment]
Hello. @notnonot , sorry for the super late reply, we are just about to refresh SOCA soon. Do you still need any assistance or I am ok to close this ticket?
